### ISSUE TITLE
Scheduled requests

### ISSUE THREAD

**Issue by krockpot** [MrPickles/dtl#1]
I want to be able to say: SL? in an hour or SL? later today and have the bot ping people like 10-15 minutes before that time

**Comment by MrPickles** [comment]
@krockpot Resolved via https://github.com/MrPickles/dtl/commit/a26388dfe8b3b58d49ad162ca66fbffb6eb24f3c

You can say something like `SL in 30 minutes?`, and the bot will remind you after the specified duration.
