### ISSUE TITLE
Please add stonks trigger word

### ISSUE THREAD

**Issue by zxlin** [MrPickles/dtl#2]
![stonks](https://cdn.drawception.com/drawings/736593/bjD99rQk2c.png)

**Comment by MrPickles** [comment]
Any other trigger words? I think you've mentioned other words before too.

**Comment by zxlin** [comment]
I think just this one rn

**Comment by MrPickles** [comment]
Resolved in https://github.com/MrPickles/dtl/commit/07c9c60b9633c1649140081d2e65687ed40eeca5
