### ISSUE TITLE
Link to the "are you sure" gif is broken 

### ISSUE THREAD

**Issue by MrPickles** [MrPickles/dtl#21]
This is the link: https://cdn.discordapp.com/attachments/428695150294859790/1050522089200816138/D2A84706-EC25-493B-862E-1CA856C523DA.gif

It seems like assets uploaded to Discord may not have infinite retention (or the URL might have changed).

https://github.com/MrPickles/dtl/blob/4e15c8a0635cc992aca042f17c80a6258a0453d3/dtl/gifs.py#L30

**Comment by MrPickles** [comment]
cc @zxlin who made the original gif

**Comment by zxlin** [comment]
i wasn't the original creator and I don't think i have a copy anymore either

**Comment by MrPickles** [comment]
Sounds good, removed in https://github.com/MrPickles/dtl/commit/a94aa4214a35a185a039a56cbaad240eee5dbb58.
