### ISSUE TITLE
Add Troy Pizza Time

### ISSUE THREAD

**Issue by zxlin** [MrPickles/dtl#3]
![https://media1.tenor.com/images/fcf5177d22199e1235bbbb1a4cab7fe7/tenor.gif?itemid=4891734](https://media1.tenor.com/images/fcf5177d22199e1235bbbb1a4cab7fe7/tenor.gif?itemid=4891734)

https://media1.tenor.com/images/fcf5177d22199e1235bbbb1a4cab7fe7/tenor.gif?itemid=4891734

**Comment by MrPickles** [comment]
https://github.com/MrPickles/dtl/commit/7477cc513a7540ef8eeea1260c43635a6765ff5c

There's now 50/50 chance of getting the spiderman and troy gifs
